apiVersion: apps/v1
kind: Deployment
metadata:
  name: ais-ifm
  labels:
    product: actimize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ais
      tier: web
  template:
    metadata:
      labels:
        app: ais
        tier: web
    spec:
      containers:
      - name: bootcamp-container
        image: jocatalin/kubernetes-bootcamp:v2
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
